spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.34.132.3:3306/tamlaguk?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: s5554549

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true

  data:
    redis:
      host: 3.34.132.3
      port: 6379

  jwt:
    header: Authorization
    prefix: "Bearer "
    secret: bW92aWVNYXRlLXNwcmluZy1ib290LXByb2plY3Qtand0LXNlY3JldC1rZXkK
    access-token-expire-time: 1800000 # 30? ???
    refresh-token-expire-time: 432000000 # 5? ???

  servlet:
    multipart:
      enabled: true                   # ???? ??? ???? (default: true)
      file-size-threshold: 0B         # ??? ???? ???? ?? ???? ???? ?? ?? (default: 0B)
      location: /usr/share/temp       # ???? ??? ??? ???? ??? ?? (default: WAS ? ??)
      max-file-size: 30MB             # ?? ??? ?? ??? (default: 1MB)
      max-request-size: 30MB          # ?? ??? ?? ??? (default: 10MB)

# aws
cloud:
  aws:
    s3:
      bucket: gotogether123
    credentials:
      accessKey: AKIAU6GDVXZVF6LZVKLJ
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false